<?php

namespace Proxies\__CG__\SamaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Consultation extends \SamaBundle\Entity\Consultation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SamaBundle\\Entity\\Consultation' . "\0" . 'idconsult', '' . "\0" . 'SamaBundle\\Entity\\Consultation' . "\0" . 'dateconsult', '' . "\0" . 'SamaBundle\\Entity\\Consultation' . "\0" . 'diagnostic', '' . "\0" . 'SamaBundle\\Entity\\Consultation' . "\0" . 'idpatientCons', '' . "\0" . 'SamaBundle\\Entity\\Consultation' . "\0" . 'idmedecinCons'];
        }

        return ['__isInitialized__', '' . "\0" . 'SamaBundle\\Entity\\Consultation' . "\0" . 'idconsult', '' . "\0" . 'SamaBundle\\Entity\\Consultation' . "\0" . 'dateconsult', '' . "\0" . 'SamaBundle\\Entity\\Consultation' . "\0" . 'diagnostic', '' . "\0" . 'SamaBundle\\Entity\\Consultation' . "\0" . 'idpatientCons', '' . "\0" . 'SamaBundle\\Entity\\Consultation' . "\0" . 'idmedecinCons'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Consultation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdconsult()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdconsult();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdconsult', []);

        return parent::getIdconsult();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateconsult($dateconsult)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateconsult', [$dateconsult]);

        return parent::setDateconsult($dateconsult);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateconsult()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateconsult', []);

        return parent::getDateconsult();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiagnostic($diagnostic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiagnostic', [$diagnostic]);

        return parent::setDiagnostic($diagnostic);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiagnostic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiagnostic', []);

        return parent::getDiagnostic();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpatientCons(\SamaBundle\Entity\Patient $idpatientCons = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpatientCons', [$idpatientCons]);

        return parent::setIdpatientCons($idpatientCons);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpatientCons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpatientCons', []);

        return parent::getIdpatientCons();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdmedecinCons(\SamaBundle\Entity\Medecin $idmedecinCons = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdmedecinCons', [$idmedecinCons]);

        return parent::setIdmedecinCons($idmedecinCons);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdmedecinCons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmedecinCons', []);

        return parent::getIdmedecinCons();
    }

}
