<?php

namespace Proxies\__CG__\SamaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Medecin extends \SamaBundle\Entity\Medecin implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'idmedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'nommedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'prenommedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'addressemedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'emailmedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'telmedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'sexemedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'cabinetmedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'specialitemedecin'];
        }

        return ['__isInitialized__', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'idmedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'nommedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'prenommedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'addressemedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'emailmedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'telmedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'sexemedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'cabinetmedecin', '' . "\0" . 'SamaBundle\\Entity\\Medecin' . "\0" . 'specialitemedecin'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Medecin $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdmedecin()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdmedecin();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdmedecin', []);

        return parent::getIdmedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setNommedecin($nommedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNommedecin', [$nommedecin]);

        return parent::setNommedecin($nommedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getNommedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNommedecin', []);

        return parent::getNommedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenommedecin($prenommedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenommedecin', [$prenommedecin]);

        return parent::setPrenommedecin($prenommedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenommedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenommedecin', []);

        return parent::getPrenommedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressemedecin($addressemedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressemedecin', [$addressemedecin]);

        return parent::setAddressemedecin($addressemedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressemedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressemedecin', []);

        return parent::getAddressemedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailmedecin($emailmedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailmedecin', [$emailmedecin]);

        return parent::setEmailmedecin($emailmedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailmedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailmedecin', []);

        return parent::getEmailmedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelmedecin($telmedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelmedecin', [$telmedecin]);

        return parent::setTelmedecin($telmedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelmedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelmedecin', []);

        return parent::getTelmedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexemedecin($sexemedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexemedecin', [$sexemedecin]);

        return parent::setSexemedecin($sexemedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexemedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexemedecin', []);

        return parent::getSexemedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCabinetmedecin($cabinetmedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCabinetmedecin', [$cabinetmedecin]);

        return parent::setCabinetmedecin($cabinetmedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCabinetmedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCabinetmedecin', []);

        return parent::getCabinetmedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecialitemedecin($specialitemedecin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecialitemedecin', [$specialitemedecin]);

        return parent::setSpecialitemedecin($specialitemedecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecialitemedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecialitemedecin', []);

        return parent::getSpecialitemedecin();
    }

}
