<?php

namespace Proxies\__CG__\SamaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Patient extends \SamaBundle\Entity\Patient implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'idpatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'nompatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'prenompatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'sexepatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'datenaisspatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'addressepatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'telpatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'agepatient'];
        }

        return ['__isInitialized__', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'idpatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'nompatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'prenompatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'sexepatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'datenaisspatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'addressepatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'telpatient', '' . "\0" . 'SamaBundle\\Entity\\Patient' . "\0" . 'agepatient'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Patient $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdpatient()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdpatient();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpatient', []);

        return parent::getIdpatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setNompatient($nompatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNompatient', [$nompatient]);

        return parent::setNompatient($nompatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getNompatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNompatient', []);

        return parent::getNompatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenompatient($prenompatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenompatient', [$prenompatient]);

        return parent::setPrenompatient($prenompatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenompatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenompatient', []);

        return parent::getPrenompatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexepatient($sexepatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexepatient', [$sexepatient]);

        return parent::setSexepatient($sexepatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexepatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexepatient', []);

        return parent::getSexepatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatenaisspatient($datenaisspatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatenaisspatient', [$datenaisspatient]);

        return parent::setDatenaisspatient($datenaisspatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatenaisspatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatenaisspatient', []);

        return parent::getDatenaisspatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressepatient($addressepatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressepatient', [$addressepatient]);

        return parent::setAddressepatient($addressepatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressepatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressepatient', []);

        return parent::getAddressepatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelpatient($telpatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelpatient', [$telpatient]);

        return parent::setTelpatient($telpatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelpatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelpatient', []);

        return parent::getTelpatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgepatient($agepatient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgepatient', [$agepatient]);

        return parent::setAgepatient($agepatient);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgepatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgepatient', []);

        return parent::getAgepatient();
    }

}
